apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-page
spec:
  replicas: 1
  selector:     
    matchLabels:
     app: myos
  template:
    metadata:
      labels:
        app: myos
    spec:
      containers:
      - name: login
        image: mk14492/login_page4
    

