---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebbokloginpage
spec:
  replicas: 1
  selector:     
    matchLabels:
     app: myos
  template:
    metadata:
      labels:
        app: myos
    spec:
      containers:
      - name: login
        image: anilsb06/facebookloginpage
