apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginpage1
spec:
  replicas: 1
  selector:     
    matchLabels:
     app: myos
  template:
    metadata:
      labels:
        app: myos
    spec:
      containers:
      - name: login
        image: anilsb06/facebok_login1
---
apiVersion: v1
kind: Service
metadata:
  name: facebook-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: login

