name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-vm

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t webapp . 
    - name: Run container
      run: docker run -itd -p 90:80 webapp
