name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t webapp .
      
  start:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: starts the cntainer 
      run: |
        echo "running"
        docker run -itd -p 96:90 webapp
